(getgov-bob) Ticket #1530: Warning messages
cisagov/getgov pull request #1846
Opened 2024-02-29 15:59 UTC by zandercymatics

## Ticket

Resolves #1530

## Changes

- `admin.py`
  - Added a custom change form template for domain application (for the delete modal)
  - Modified delete_view for DomainAdmin to include a custom delete confirmation page
- `get-gov-admin.js`
  - Modified the `createPhantomModalFormButtons` function to make it more specific
  - Added a `displayModalOnDropdownClick` function that displays a modal on status change
- `_admin.scss`
  - Added styling to li elements inside modals to match <p> tags.
- Added `domain_application_change_form.html`
- Modified `domain_change_form.html`
- Added `domain_delete_confirmation.html`
- Added tests in `test_admin.py` 

## Context for reviewers
On Django Admin, this ticket adds confirmation modals in three places:
1. When the "Place hold" button is pressed (Found with a Domain in the state "ready")
2. When the "Remove from registry" button is pressed
3.  When the status on a DomainRequest is changed to "ineligible" (before save)

A custom delete confirmation message is displayed in these two places:
1. When the "delete" button is pressed for a domain object
2. When the "delete selected domains" button is pressed on the tables

## Setup
1. Navigate to Django Admin
2. Navigate to Domain Request and select a record
3. Change the status of a domain to "ineligible". A modal should display. When clicking cancel, the status should revert.
4. Navigate to Domain and select a record in the state "Ready"
5. The "Place hold" and "Remove from registry" buttons (pressed in that order) should both display modals
6. Click the "delete" button on the bottom of the page. The delete confirmation page that you get redirected to should have custom content 
7. Navigate back to the Domain table view. Delete a record from there. Like before, a custom delete confirmation page should be presented.

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [x] Met the acceptance criteria, or will meet them in a subsequent PR
- [x] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

2024-03-06 22:37 UTC, erinysong commented
Deployed this to my sandbox if anyone else can benefit from using it

2024-03-06 22:39 UTC, erinysong commented
UI question: Do we want the modal buttons be bullet points? This may have been already discussed and I know Django admin has limited UI capabilities, but I was wondering if it'd be possible to remove them. Minor nit since this will be analyst facing and acknowledge that functionality takes precedence
<img width="537" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/bb2de7f8-b50c-4fbe-9ad9-819646285cc4">

2024-03-06 22:44 UTC, erinysong commented
This is more of a design question but what should happen if I visit a domain application record, make the status Ineligible to prompt the warning modal, and click cancel? Should the status still remain Ineligible or should it switch back to the previous status? Currently when I click cancel/away from the warning modal, the status still remains ineligible. Since this is a warning modal and for an important-but-nonbreaking change, I'm wondering if there's a way to inform the user they're making a domain application Ineligible but not require them to acknowledge that they're doing so.
<img width="664" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/b2eaafdf-3448-4205-9fb6-501102d0f250">
<img width="640" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/917a39ec-9bee-4233-8bcc-58b81cbede32">

2024-03-06 23:38 UTC, erinysong commented
May be misunderstanding what Place Hold does, but when I create a add domain from admin to test, I have the option to Place Hold and from the Place Hold modal, I can directly create a new domain that does not have a Hold status. I was wondering if Place Hold should be accessible from the Add a New Domain page and if so, should the modal do this?

1. Create a new domain hold-from-add-domain.gov
<img width="1109" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/f02bf1c2-7a37-4039-8407-0b7c1b296758">
2. Click on the Place Hold button, prompting the Place Hold warning modal. The status is blank for Domain or New status.  
<img width="1094" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/0e9e6314-a66f-4fa3-8c75-b76a44d7ff3b">
3. Clicking the confirmation button on the Place Hold modal adds the domain. 
<img width="1113" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/af8826d2-7655-4d9e-870b-1ce469535c0d">
4. The status of the domain is Unknown despite placing a hold on the domain.
<img width="1101" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/c428a779-0d9f-4643-9d37-73aac1744b0a">

2024-03-07 23:33 UTC, erinysong commented
Thank you for the heads up about the static assets - that successfully removed the bullet points and got the right behavior on the cancel button! I also ran the commands you gave and updated them on my sandbox. The domain application status now reverts back to its initial status if you click cancel on the modal, but it still seems to switch to Ineligible if you close the modal by clicking the close button or clicking outside of the modal. Should we add the same logic we have to the cancel button to the close modal button and the event the user clicks away from the button?
Including the flow I used for visual reference

1. Domain application is in review. Changed the status to Ineligible
<img width="592" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/0baa68ae-edc8-4ce2-b30e-609179565f1d">
2. Click on the close button on the top right corner of the modal or anywhere outside of the modal. The status change to Ineligible goes through as opposed to the cancel button, which reverts the domain application to its initial status
<img width="671" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/6f4daf2a-07c0-44be-8c7d-2af5a33ccc46">
<img width="651" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/076d58f6-cdab-45af-817a-c30f5c49ad4e">

2024-03-07 23:42 UTC, erinysong requested changes
The modals look great! Wrote down on a couple edge cases but let me know if any of these are a result of static assets that aren't properly on my sandbox. I'm currently unable to access the on hold modal flow because all my domains have status Unknown which I'll try to fix within my sandbox, but posting here in case anyone is able to test the On Hold flow before I'm able to fix my data.

1. Replicating the modal cancel button's behavior when you also close the close button and/or click outside of the modal
2. Putting a domain on hold when you add domain.

2024-03-07 23:42 UTC, erinysong commented on src/registrar/templates/django/admin/domain_application_change_form.html
> +            <button
Should we also connect the same logic used for "_cancel_application_ineligible" to this button + the event the user clicks outside of the modal?

2024-03-11 18:30 UTC, erinysong commented
Successfully accessed Place Hold modal on domain in Ready state. User can also remove hold on a domain without being prompted by a warning modal.
<img width="824" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/e19c2d6f-afb7-43ce-a708-8e53b8676524">

2024-03-11 18:33 UTC, erinysong approved these changes
Confirmed that all warning modals and pages display successfully! Looks good to go after merging with main 🎉
Have a non-blocking comment on if we'd want to also have a warning modal when a user removes a hold on a domain, but that is outside the scope of this ticket since it'd depend on design and content decisions.

2024-03-15 20:39 UTC, Katherine-Osos approved these changes

2024-03-15 21:19 UTC, merged