Ticket #2228: Assign investigator to self
cisagov/getgov pull request #2304
Opened 2024-06-12 19:07 UTC by zandercymatics

## Ticket

Resolves #2228 

## Changes

- Adds a "assign to me" button under the investigator field in django admin (for domain request)
- Adds a small javascript hook to enable this behaviour

## Context for reviewers
The investigator field is a little different than our normal selectors: it uses the select2 library.
To trigger a change event on the field, we need to use the relevant jquery selector rather than .value

## Setup
1. Go to /admin
2. Click Domain Request
3. Select a record (with no investigator)
4. Click the assign to me button underneath the investigator field (see attached)

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [x] Created/modified automated tests
- [x] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [x] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [x] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [x] Checked keyboard navigability
- [x] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots
![image](https://github.com/cisagov/manage.get.gov/assets/141044360/b32fe56f-3d73-4e90-9a0b-5870bd674de2)

2024-06-13 15:30 UTC, kristinacyin reviewed
Reviewing this right now! 

I noticed that the "Assign to me" button disappears as soon as an investigator is selected. I'm wondering if it might be a good idea to have the "Assign to me" button stay if the investigator selected isn't the user. It could be possible, for example, for a domain request to change hands from one investigator to another if it's a particularly tricky case. What do you think?

2024-06-13 17:04 UTC, kristinacyin submitted a review, later dismissed
It seems at least that people are partial to my idea [on Slack](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1718293395349429?thread_ts=1718217946.956789&cid=C05BDEA3C11), would you mind changing it so that the "Assign to me" button perpetuates if the investigator assigned is not the user? I'll also change the ticket AC, thank you!

2024-06-13 19:32 UTC, kristinacyin requested changes
Thank you for implementing the changes! I noticed that even when I have already assigned **myself** as the investigator, the "Assign to me" button still stays (screenshot below). I think that's the only state in which we can remove the "Assign to me" button, if possible. I don't have strong opinions about this so let me know if it's too much of a hassle

![image](https://github.com/cisagov/manage.get.gov/assets/140533113/523c226e-56e1-4f3f-979f-77bf88e3dfbc)

2024-06-13 20:38 UTC, kristinacyin approved these changes
Looks great! Great job!!! 🥇

2024-06-14 20:49 UTC, CocoByte approved these changes
LGTM

2024-06-14 20:49 UTC, CocoByte commented on src/registrar/assets/js/get-gov-admin.js
> +        assignSelfButton.parentElement.style.display = this.value === currentUserId ? "none" : "flex";
Nice attention to style detail here.  Usually, I would view this as a symptom of design architecture needing an update, but given what we are working with I think this is perfectly fine.

2024-06-17 14:40 UTC, merged