(on getgov-za) Ticket #2421/#2422:  Missing first name and last name gets a green checkmark next to “Unknown” and make field label consistent
cisagov/getgov pull request #2423
Opened 2024-07-03 18:12 UTC by zandercymatics

## Ticket

Resolves #2421
Resolves #2422

## Changes

- When the input fields are changed, we update the "readonly label" accordingly such that these two fields are in sync.
- Minor code flow changes to account for this.

## Context for reviewers
A bug was found wherein the full name field on the Finish User Profile page would display the "complete" icon when we were missing data for the users name.

When the user would save in this state, the page would still show that these fields were missing data - but it was not immediately obvious as it displayed that it was complete.

This bug was being caused by an edge case regarding the "full_name" field being a) required and b) defaulted to "Unknown" on None instead of just being None.

This PR changes the flow such that full_name will always be none if we don't have any values for first name or last name. Then, we include javascript that updates this readonly value for the full name and other fields.

## Setup
1. Enable the profile flag
2. Edit your user such that you are missing some required data. More specifically, remove the name fields and an unrelated field like title.
3. Go to home (you should be redirected to the finish user setup page)
4. Edit one of your name fields and add a first name and last name. Do _not_ add a title. When you click save, your changes should now reflect on the name fields
5. Do the same for the name fields but in reverse such that your testing title.

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

2024-07-03 19:57 UTC, rachidatecs commented on src/registrar/forms/user_profile.py
> +        self.fields["full_name"].widget.attrs['required'] = 'required'
Why the workaround?

2024-07-03 19:57 UTC, rachidatecs commented on src/registrar/assets/js/get-gov.js
> +              inputField.classList.add("text-base")
Why the JS class assignemnt? And where's the readonlyField.innerHTML = inputFieldValue (for phone and title)?

2024-07-08 19:54 UTC, rachidatecs commented on src/registrar/assets/js/get-gov.js
> +              let lastName = document.querySelector(`#id_last_name`);
Agree, commit

2024-07-08 19:56 UTC, rachidatecs commented on src/registrar/tests/test_views.py
> +    def test_new_user_with_empty_name_profile_feature_on(self):
def test_new_user_with_empty_name_can_add_name(self):

2024-07-16 19:25 UTC, CocoByte requested changes
Got a few comments for you to look at.

2024-07-16 19:25 UTC, CocoByte commented on src/registrar/assets/js/get-gov.js
> +        let editableFormGroup = button.parentElement.parentElement.parentElement;
Seems using an ID or class would be better...is there an inconsistency in the DOM that prevents a more proper lookup?

2024-07-16 19:25 UTC, CocoByte commented on src/registrar/assets/js/get-gov.js
> +              // this is difficult to achieve otherwise by modifying the .readonly property.
Appreciate the comments here

2024-07-16 19:25 UTC, CocoByte commented on src/registrar/assets/sass/_theme/_base.scss
> +    div.input-with-edit-button__readonly-field {
This strips away the red coloring for other readonly fields.  Did we want to do this?

2024-07-16 19:25 UTC, CocoByte commented on src/registrar/forms/user_profile.py
> +        if self.instance.first_name and self.instance.last_name:
Seems like this logic should be inside of get_formatted_name(). What was the reasoning for doing these checks here?

2024-07-16 19:25 UTC, CocoByte commented on src/registrar/models/contact.py
> +    def get_formatted_name(self, return_unknown_when_none=True):
Is there ever a case where return_unknown_when_none != True?

2024-07-17 15:49 UTC, kristinacyin requested changes
After I deleted my first name and last name in admin, I saw this:

![image](https://github.com/user-attachments/assets/f03de331-21f3-473f-9db6-4024060e37b2)

While I didn't get "Unknown", my answer was blank and I still got the green check mark

2024-07-17 15:52 UTC, kristinacyin commented
Also, I'm going to crosspost this question in #dotgov-design for others' input:


I noticed that the order is slightly different between **/finish-profile-setup** and **/user-profile**

/user-profile has the order of Name, Title, Org Email, Phone
![image](https://github.com/user-attachments/assets/6341d812-8540-4692-b18f-f70ac7653be7)

While /finish-profile-setup has the order of Name, Org Email, Title, Phone
![image](https://github.com/user-attachments/assets/0391d520-d339-4360-b122-007a8372a7c2)

I think we should make both of them consistent. Does it make more sense to have Org Email or Title first? Personally, it makes more sense to me to have Title first

2024-07-17 17:35 UTC, kristinacyin approved these changes
LGTM! 🥇

2024-07-17 17:51 UTC, CocoByte commented on src/registrar/assets/js/get-gov.js
> +        let editableFormGroup = button.parentElement.parentElement.parentElement;
Seems like a red flag architecture-wise, but I see the reasoning.  Sounds good

2024-07-17 17:54 UTC, CocoByte commented on src/registrar/assets/sass/_theme/_base.scss
> +    div.input-with-edit-button__readonly-field {
It's not really an issue...The only thing is that when we get specific like this we rely more and more on several "red" settings to basically stay in sync, which seems prone to breakages.  We do this alot already in our scss architecture, though, so I will leave it.  I've noticed that we are gradually refactoring our scss as we go so it shouldn't be too much of a problem.

2024-07-17 17:55 UTC, CocoByte commented on src/registrar/forms/user_profile.py
> +        if self.instance.first_name and self.instance.last_name:
Got it...seems like an inconsistent UI rule, but I won't argue the ACs this time around.

2024-07-17 18:40 UTC, CocoByte approved these changes
LGTM!

2024-07-17 19:09 UTC, merged