Update product_strategy.md
cisagov/getgov pull request #463
Opened 2023-03-13 15:01 UTC by calerubensteingsa

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

2023-03-13 21:07 UTC, michelle-rago reviewed
LGTM!

2023-03-14 16:48 UTC, michelle-rago approved these changes

2023-03-15 14:05 UTC, h-m-f-t requested changes
Thanks for preparing, Cale! Sorry to have missed these in the doc.

2023-03-15 14:05 UTC, h-m-f-t commented on docs/product/product_strategy.md
> +U.S.-based government organizations and publicly controlled entities lack a clear, usable, and efficient way to apply for, register, and manage .gov domains and related infrastructure to build public
I think this should change: "to build public trust in their online services and communications"

2023-03-15 14:05 UTC, h-m-f-t commented on docs/product/product_strategy.md
> +CISA lacks a scalable, efficient, and secure method of managing the .gov TLD program that helps government agencies build public trust of their website and communications.
Same.

2023-03-15 18:44 UTC, calerubensteingsa reviewed
Updated (I think!)

2023-03-16 19:01 UTC, h-m-f-t approved these changes
Thanks!

2023-03-22 19:45 UTC, merged