864 - Fix text too light on certain pages in dark mode (user facing pages)
cisagov/getgov pull request #866
Opened 2023-08-10 20:19 UTC by rachidatecs

## 🗣 Description ##

- Remove brod 'body' CSS selector when setting color in dark mode (initially, to fix text too dark on change_list_results tables)
- Tested locally in django admin and on user facing pages, using system and django admin dark/light mode toggles.

## 💭 Motivation and context ##

Closes #864

2023-08-11 22:03 UTC, abroddrick requested changes
![image](https://github.com/cisagov/getgov/assets/109625347/ed24b4e0-9f39-415e-977a-4c5e43b4e534)
"Domain Information" now fails for contrast when system is in dark mode to begin with. it also defaulted to light at first and I clicked the toggle. not sure if that is related

2023-08-14 15:38 UTC, rachidatecs commented
Fixed. The defaulting to light at first is interesting and unexpected. I assume you double checked that your system setting is still dark mode?

2023-08-14 16:37 UTC, zandercymatics requested changes
Built locally from your branch (not on sandbox as I am not added to fixtures on rjm), but this fix doesn't appear to be working for me on Chrome when the system style is set to dark:
![image](https://github.com/cisagov/getgov/assets/141044360/0c2eacfe-1db9-4771-9a45-7f25a6cd491e)

That said, when I use the style button in admin (and change to dark), it works as expected

2023-08-14 16:46 UTC, rachidatecs commented
@zandercymatics, if you checkout the branch while docker was up, you might need to run `npx gulp compile` and clear cache/refresh. Lemme know.

2023-08-14 17:18 UTC, zandercymatics commented
@rachidatecs Looks like that fixed it! Everything else seems to be working as expected, the only exception is the 'None Available' text which seems to be colored black in dark mode. This seems to be agnostic when it comes to whether its system or the button... Let me know if this is not reproducible  
![image](https://github.com/cisagov/getgov/assets/141044360/5c1e43d4-3641-43b5-b393-0184d3793171)

2023-08-14 18:23 UTC, rachidatecs commented
Good catch. On it.

2023-08-14 19:02 UTC, rachidatecs commented
Fixed

2023-08-14 19:52 UTC, zandercymatics commented
@rachidatecs Looks good! Doesn't seem to be broken anymore

2023-08-14 19:53 UTC, zandercymatics approved these changes

2023-08-16 16:09 UTC, merged